import { defineCloudflareConfig } from "@opennextjs/cloudflare";
import r2IncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-incremental-cache";

/**
 * OpenNext Cloudflare configuration.
 * https://opennext.js.org/cloudflare/get-started
 *
 * Round 12 R12-U3 (4/4 unanimous): enabled R2 incremental cache because every
 * HTML response was returning x-nextjs-cache: MISS — Cloudflare Workers don't
 * auto-cache responses, so OpenNext needs an explicit cache backend or
 * prerendered pages are regenerated by the Worker on every request.
 *
 * Prerequisites for the binding to resolve at runtime:
 *   1. Create an R2 bucket in the Cloudflare dashboard (suggested name:
 *      `jara-international-next-cache`).
 *   2. The wrangler.toml `[[r2_buckets]]` entry with binding =
 *      "NEXT_INC_CACHE_R2_BUCKET" must point at that bucket.
 *
 * Without the bucket the deploy will succeed but cache writes will fail
 * silently — the binding name `NEXT_INC_CACHE_R2_BUCKET` is the convention
 * the r2IncrementalCache override expects (see node_modules/@opennextjs/
 * cloudflare/dist/api/overrides/incremental-cache/r2-incremental-cache.d.ts).
 */
export default defineCloudflareConfig({
  incrementalCache: r2IncrementalCache,
});
